group: edge
dist: xenial
sudo: required
language: node_js
node_js: 8

env:
  global:
    TRAVIS_KUBE_VERSION=1.11

before_install:
  - ./tools/travis/start-cluster.sh
  - ./tools/travis/start-openwhisk.sh

script:
  - echo hi
